export const REQUEST_DISHES = "REQUEST_DISHES";
export const REQUEST_DISHES_SUCCESS = "REQUEST_DISHES_SUCCESS";
export const REQUEST_DISHES_FAILURE = "REQUEST_DISHES_FAILURE";
export const SELECT_DISH = "SELECT_DISH";
